### ISSUE TITLE
[BUG] Discrepency when determining result type's types

### ISSUE THREAD

**Issue by vector-of-bool** [soasis/text#11]
The below sample will fail to compile.

```c++
#include <ztd/text.hpp>

void repro() {
    std::string     str;
    ztd::text::utf8 enc;
    auto            enc_state = ztd::text::make_encode_state(enc);
    auto            dec_state = ztd::text::make_decode_state(enc);
    ztd::text::transcode_into(str,
                              enc,
                              str,
                              enc,
                              ztd::text::pass_handler{},
                              ztd::text::pass_handler{},
                              dec_state,
                              enc_state);
}
```

`basic_transcode_into` uses `using _WorkingOutput = __recontsruct_t<Output>` and declares a variable `_WorkingOutput __working_output`. Later, in a deeper call to `__super_basic_transcode_one()`, the output range type for the `transcode_result` is determined as the return type of `__basic_encode_one()`. `__basic_encode_one` uses a series of `if constexpr` checks to determines its return type. The type of `transcode_result::output` can differ from `__working_output`. `basic_transcode_into` then attempts to assign `__transcode_result.output` into `__working_output`, which will fail if they are not the same (or at least convertible).

In this case, the `__basic_encode_one()` is returning an `unbounded_view<std::string::iterator>`, whereas the `__working_output` is of type `subrange<std::string::iterator>`. I cannot understand the `if constexpr` checks enough to tell _why_ the branch returning an `unbounded_view` is selected.

**Comment by ThePhD** [comment]
Ooh, this is my bad. I was supposed to mention that  all the `ztd::text::(de|en|trans)code_into` functions require a range and aren't really equipped to handle non-ranges right now. I've been trying to avoid developing a `is_container_v` trait alongside a `is_view_v` trait, because I didn't want to re-implement all of ranges (because at that point that's basically what you're doing, sans the cool adapters and other actual concrete range types).

But, if I want this code to work (and I kind of do?), I probably will have to develop that. And also improve the core of `ztd::text::transcode`/`ztd::text::transcode_into`.... bweh!

**Comment by vector-of-bool** [comment]
In my actual code, I'm not using a `std::string`, but an `ad_hoc_range` ([refer](https://github.com/vector-of-bool/neo-fun/blob/develop/src/neo/ad_hoc_range.hpp)). I see the same result in either.
