### ISSUE TITLE
Request: Add port for vcpkg

### ISSUE THREAD

**Issue by TerensTare** [soasis/text#20]
First I'd like to thank you and all the contributors of the library for all your work done so far.

Going further, I'd like to propose making the library available through vcpkg (and other package managers) to ease up the process of integrating it on different projects, let them be existing or new ones. The library is header-only so should be (relatively) easy to integrate and sol2's "model" could be as well adapted for the library (not sure if there is any problem related to this).

**Comment by ThePhD** [comment]
Yeah, I'd like to put this on / outfit it with these build systems:

- [x] cmake
- [ ] build2
- [ ] vcpkg
- [ ] conan
- [ ] hunter (? is that still alive? is that even its name anymore?)
- [ ] meson

Contributions to that effect are welcome. The library might not be header-only forever but I'm okay with breaking downstream folk who rely on this since it'd be a compile-time error and the fix would be "just point yourself at the new Cmake / meson / {etc.} files".

**Comment by TerensTare** [comment]
Great, I can help with writing and testing the vcpkg port.

**Comment by nickelpro** [comment]
vcpkg issue: https://github.com/microsoft/vcpkg/issues/23661

"Works for me" PR: https://github.com/microsoft/vcpkg/pull/23662

Need to figure out why the build is choking on Windows. Also my port is probably bad since I'm rolling ztd.cmake and ztd.idk into the ztd.text portfile instead of porting each separately

**Comment by ThePhD** [comment]
It might help to do them separately. But, the interface for getting to the build logs is inscrutable, so I am not sure what is failing, exactly...

**Comment by nickelpro** [comment]
I'm working on it, and inspecting similar packages in ports it seems like my approach is actually the standard one for things like this.

**Comment by nickelpro** [comment]
This now works, we'll see what MS people think of it

**Comment by nickelpro** [comment]
Added to vcpkg

**Comment by ThePhD** [comment]
LEt'S GOOOOOO!!!!!!
